### ISSUE TITLE
Hierarchy columns in Preview are not available in the model - Weekly template

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#150]
If you choose the Weekly template and preview the Dates table, you will see that the Year-XXX hierarchies contain columns with no datatype and cannot be inspected: this is because those columns are not available in the model and we don't know their properties.

<img width="295" alt="Power_BI" src="https://user-images.githubusercontent.com/9072177/158057541-188eec1c-21bc-4f11-9992-b448019748a3.png">

This doesn't happen with other templates.

**Comment by marcosqlbi** [comment]
@danieleperilli **we should remove the data type symbol for every level in a hierarchy** because it is more consistent. The way it works now could be misleading - showing a data type of another column. It does not worth the effort moving to the client all the information just to provide the data type - we should include the underlying column name if we wanted a real difference but it's not very important and it would add confusion to the UI.

**Comment by danieleperilli** [comment]
Completed #392

**Comment by albertospelta** [comment]
Fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
