### ISSUE TITLE
Dataverse Directquery > Manage Dates - Error in Model Check 

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#239]
### Describe the problem

Attempting to create a calendar throws error. - (screenshot included)

Error Query (4, 55) Column 'RowNumber-<guid>' cannot be found or may not be used in this expression

### Bravo version

0.9.8121.26944

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

### Steps to reproduce the behavior

Go to Manage Dates.
Attempt to create a calendar (using all default settings)

### Screenshots

<img width="232" alt="Bravo Date Check Error" src="https://user-images.githubusercontent.com/6276300/160619242-d8f9779d-496e-4907-b1e3-d695f142eb1e.png">

**Comment by ThysvdW** [comment]
Experienced the same issue. Was due to Measures being located in a seperate "# Measures" table. Thought it could relate to the "Measures" name, and renamed the table to something else, but the error still persist. When I moved the measures to the corresponding fact tables, I was able to create the date table without issue.

**Comment by albertospelta** [comment]
Hi @ThysvdW, is table "# Measures" a calculated table?

**Comment by ThysvdW** [comment]
Yes, it is a calculated table. The error happens when you open the Date tab. Haven't tried setting the Time Intelligence function off. My scenario is that the date table was already generated by Bravo and after that - we created some measures, and then wanted to add the Time Intelligence to the created measures in the calculated table.

**Comment by albertospelta** [comment]
Fixed in [0.9.3](https://github.com/sql-bi/Bravo/releases/tag/v0.9.3)
