### ISSUE TITLE
wwwroot\bravo.ico cannot be found

### ISSUE THREAD

**Issue by gdeckler** [sql-bi/Bravo#261]
### Describe the problem

Running Bravo from the Power BI External tools menu crashes with the error that the wwwroot\bravo.ico file cannot be found. 

### Bravo version

0.0.0.999

### Tabular model

Power BI Desktop, import mode

### Power BI

March 2022

### Steps to reproduce the behavior

1. Add the .pbitool.json file to the External Tools directory
2. Launch Bravo

**Comment by albertospelta** [comment]
Hi @gdeckler, are you experiencing this error with a version compiled from source code or installed via the .MSI installer?
The error message seems to indicate that the file is missing because the application has not been published but only compiled.

https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio?pivots=dotnet-5-0

![image](https://user-images.githubusercontent.com/1957788/161081943-df0bf20c-6e1e-49c8-a0a5-6bc94f6a5b4a.png)

**Comment by gdeckler** [comment]
Compiled only, will have to see about publishing, didn't see any note about that in Git

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by albertospelta** [comment]
Publishing using the parameters shown in the image above should resolve the error.
If the issue is not solved, please feel free to reopen the question.
