### ISSUE TITLE
Allow use of custom calendar template

### ISSUE THREAD

**Issue by bdarbonneau** [sql-bi/Bravo#325]
### The feature request

Let users customize the calendar template or chose from pre-defined templates prepared by the community or local champions.

The built-in calendar templates may not fulfill everyone requirements and may not match existing local standards in a company. 
It would be great if users could choose from different 'company-curated' templates prepared by champions.

### Proposed solution

Allow Bravo to use an alternative custom github repository for the calendar templates. This could be achieved by adding an option to enter the URL to a custom calendar configuration file which would contain the definition of the different custom calendar templates ( ex: Company-monthly, Company-monthly+week, Company-fiscal.)

**Comment by marcosqlbi** [comment]
We want to enable the ability to provide a template in a JSON file. Before that, we should complete and publish the documentation to prepare them.
In order to provide predefined templates for the company, we are exploring ideas, like using registry keys or other information that could be deployed within the company by system administrators. Or, as a minimum, to preserve the templates imported so that you don't have to read the same files multiple times. 
Please, let us know your thoughts about these options - thanks!

**Comment by bdarbonneau** [comment]
Thanks for the quick reply. Deploying GPO rules is usually a long and rigid process in companies. Downloading a JSON file 
from the company wiki and saving it to a predefined folder, a bit like Power BI custom connectors, might be easier. Or a first step.
Thanks for this great tool.

**Comment by albertospelta** [comment]
I'm closing this issue temporarily and moving to the [Enhancements](https://github.com/sql-bi/Bravo/projects/2) board.

**Comment by albertospelta** [comment]
Added in version [0.9.6](https://github.com/sql-bi/Bravo/releases/tag/v0.9.6).

Using the new template management panel on the Bravo options page it is now possible to clone an existing date template or create a new one from scratch. 

More information here:
- https://docs.sqlbi.com/bravo/options#templates 
- https://docs.sqlbi.com/bravo/customize-date-template.
