### ISSUE TITLE
Add Relative Periods (Month/Year/Day) to the Calendar selection

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#375]
### The feature request

Add relative dates to the calendar created by Time Intelligence
        VAR RelativeYear = DATEDIFF(TODAY(),[Date],YEAR)
        VAR RelativeMonth = DATEDIFF(TODAY(),[Date],MONTH)
etc.

### Proposed solution

Using a relative date calculation is only way (that I know) to filter a report page by a date range like "all dates from 6 months ago plus this month and up to 6 months in the future."

I can add a relativeMonth/relativeYear measure to the Bravo-created calendar now, but doing so 'breaks' the ability for Bravo to update Time Intelligence until I remove the additional measure.

**Comment by marcosqlbi** [comment]
Would it be good for you to customize a JSON file with your own template?
We do not want to complicate the UI in Bravo, so such a field should be always included in the templates, but we are not sure it would be commonly used. We want to include more advanced configurations, but not in the UI - mostly in JSON files.

**Comment by marcosqlbi** [comment]
The issue is that there are many different requirements. If we include all the possible columns, we end up with a complex Date table and/or a large number of configuration settings. We are exploring options, but in the v1 we would like to keep the templates we have now plus the option of a custom template (not available yet).

Please, can you elaborate on the need of storing the customized template in the file? Assuming that the custom template also includes all (or most of) the parameters, what is the purpose of executing it again on the same model? I would like to understand the use case to evaluate the possible solutions in more detail. Thanks!

**Comment by mscottsewell** [comment]
Thanks @marcosqlbi - My thoughts are around the teams working on a report - or working on a report that I updated a month ago. - If managing a PBIX becomes now dependent on external json files, then the customer process now requires a more involved source/version control setup.

**Comment by marcosqlbi** [comment]
@mscottsewell It's only the creation of a Date table in the PBIX file that depends on Bravo, once you create that Date table, it can be modified without using Bravo just as any other table in the model. 
Our idea is that creating too many parameters would undermine the usability of the tool. We are looking forward to implementing external configuration files that a company can decide to automatically deploy to employees through policies and other techniques.
