### ISSUE TITLE
Difference between VertiPaq model size and PBIX file size

### ISSUE THREAD

**Issue by ajerb** [sql-bi/Bravo#527]
### Describe the problem

Hi,
I am surprised to see the difference my Dataset size that Bravo displays VS the size that is displayed in the service or in my desktop

 ![image](https://user-images.githubusercontent.com/44672352/199777234-4fdb8493-d7c3-41a4-bd24-a517ceca261a.png)

Is there an explanation to that or is it a bug ?

### Bravo version

v1.0.0

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI desktop version October 2022

**Comment by albertospelta** [comment]
Hi @ajerb

The PBIX file on your desktop and the dataset in the service storage are both a compressed backup of your data model. When you open the PBIX report or a report on PBI service then the data model is loaded in memory in the Analysis Services process. Data loaded into memory takes more space because part of the data is not compressed so it's normal that this size - which is the one that Bravo displays - is bigger than the PBIX file on disk.

You can take a look at this video where Marco explains it in more detail https://www.youtube.com/watch?v=vI7kVVHxsiM

**Comment by ajerb** [comment]
Hi @albertospelta 
Thanks a lot, the video helped me a lot to understand it.
