### ISSUE TITLE
date/time format of column in .csv export

### ISSUE THREAD

**Issue by zenisekd** [sql-bi/Bravo#549]
### Describe the problem

Hello, today I tried to export a table with date column to .csv and then upload the .csv to Power BI again, unfortunately due to the format, power query doesn't recognize the value as date time. I have to first remove the ,000 at the end of the value and then I can convert it to date/time. Could you please fix it so that the column was immediately recognized as date/time in Power Query? Thank you.
![Capture](https://user-images.githubusercontent.com/119669511/205281901-72095e67-366b-408e-87da-a74f48a32916.PNG)

### Bravo version

1.0.0

### Tabular model

Power BI Desktop, import mode

### Power BI

October 2022

**Comment by albertospelta** [comment]
This probably happens because the PQ/.NET parser does not support the comma as a separator between the time element and its fraction, despite the fact that the [ISO-8601 specification sates](https://en.wikipedia.org/wiki/ISO_8601) that a comma is preferred.

> A decimal mark, either a comma or a dot is used as a separator between the time element and its fraction. (Following ISO 80000-1 according to ISO 8601:1-2019, it does not stipulate a preference except within International Standards, but with a preference for a comma according to ISO 8601:2004).

I just tested this command on .NET 4.7.2 and it throws a `FormatException`

`DateTime.Parse("2022-12-31 23:59:59,999")`
>System.FormatException: String was not recognized as a valid DateTime.

/cc @dgosbell 

@zenisekd I just pushed a fix, if you want to test you can try the latest internal build (`1.0.8371.29587`) by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then following the download link. Thanks!

**Comment by albertospelta** [comment]
Fixed in version [1.0.1](https://github.com/sql-bi/Bravo/releases/tag/v1.0.1)
