### ISSUE TITLE
DAX Formatting error

### ISSUE THREAD

**Issue by paulrosedigital** [sql-bi/Bravo#710]
### Describe the problem

Error 103: The requested update conflicts with the current state of the target resource.

### Bravo version

1.0.5 (1.0.8623.25801)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI desktop Version: 2.118.828.0 64-bit (June 2023)

### Steps to reproduce the behavior

Trying to format dax

### Anything else ?

Trace Id: 00-3da204d2e3baf83b6ce3e916dbf11022-e6785d14accacefa-00

**Comment by albertospelta** [comment]
Hi @paulrosedigital, the message indicates that Bravo could not apply the changes (update the DAX code) because the database was changed/updated while the format operation was in progress. Bravo uses an optimistic approach to concurrency to check whether the database has been modified before taking action to update the DAX code.

In this case, synchronizing the database using the button highlighted in the image should solve the issue. 
![image](https://github.com/sql-bi/Bravo/assets/1957788/84ea40d7-df4c-496f-890e-64910ea0256a)

If you’re still seeing issues, please feel free to post back here and we can reopen it.
