### ISSUE TITLE
Error 200 Connection Error

### ISSUE THREAD

**Issue by joelmsherman** [sql-bi/Bravo#740]
### Describe the problem

Error 200: The connection to the requested resource is not supported.

### Bravo version

0.9.4 (0.9.8158.22794)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.122.746.0 64-bit (October 2023)

### Steps to reproduce the behavior

Opened Bravo from external tool pane in Power BI desktop and got error

**Comment by albertospelta** [comment]
It seems you're using an old version of Bravo. Can you try to get the latest version first?
This is probably the same issue reported at https://github.com/sql-bi/Bravo/issues/364 and has already been fixed in a newer version of Bravo.

We are closing this issue as duplicate, but feel free to reopen it if the problem persists with the latest version.

**Comment by joelmsherman** [comment]
latest version corrected the issue.  Sorry for not searching out first and thanks!
