### ISSUE TITLE
Couldn't open Bravo Calendar when a file use a custom template created by other person.

### ISSUE THREAD

**Issue by jdmelendez** [sql-bi/Bravo#741]
### Describe the problem

Error HTTP/500: Internal Server Error.
Could not find a part of the path 'C:\Users\______\_______L\Recursos\Power Bi\Calendarios\Calendario\dist\Calendario.package.json'.

### Bravo version

1.0.6 (1.0.8693.18732)

### Tabular model

Power BI Desktop, import mode

### Power BI

Bravo, Templates, Calendar

### Steps to reproduce the behavior

Open Bravo and select manage dates.

### Anything else ?

Rastro ID: 00-6352fe7a9c202579a00efcd0bee714a5-4cd36e4efeed55ff-00

**Comment by albertospelta** [comment]
Hi @jdmelendez, thank you for reporting and sorry for not getting back to you sooner. This is a bug and, because of this, the current version of Bravo does not allow to import a `User` template, as I had suggested in https://github.com/sql-bi/Bravo/discussions/742#discussioncomment-7510506
I have identified the bug and a fix will be available shortly.

**Comment by albertospelta** [comment]
Hi @jdmelendez, the bug has been fixed and will be included in the next release. This should allow you to load a `User` template from a `.package.json` file, as I had suggested in https://github.com/sql-bi/Bravo/discussions/742#discussioncomment-7510506. If you are interested in trying a preview build, you can get it by changing the update channel from `Stable` to `Dev` in the Bravo options panel and then follow the download link.

**Comment by albertospelta** [comment]
Fixed in version [1.0.7](https://github.com/sql-bi/Bravo/releases/tag/v1.0.7)
