### ISSUE TITLE
Unable to format my DAX measures in Power bi 

### ISSUE THREAD

**Issue by vivdroid242** [sql-bi/Bravo#785]
### Describe the problem

Error 103: The requested update conflicts with the current state of the target resource.

### Bravo version

1.0.8 (1.0.8868.14547)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power Bi Desktop April 2024

### Anything else ?

Trace Id: 00-aacc87dd4759c082cf099b0ccb75c4fe-6769ce7c7a18865a-00

**Comment by albertospelta** [comment]
@vivdroid242 The error message indicates that Bravo halted formatting because it detected that the model has changed. This could occur if changes are made to the model or if a data refresh happens while Bravo is formatting the measures. In such cases, Bravo stops the task to prevent changes from being overwritten/lost. You can retry formatting after synchronizing the changes in Bravo using the `Synchronize` button. 

![image](https://github.com/sql-bi/Bravo/assets/1957788/b94ec9d0-e7fa-46e9-a04e-716a26428bdc)

I am closing this issue, but feel free to reopen it if you're still experiencing the problem.
